language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "cUPgvzDCTcc+KVN/bvxL5XCtNE98cgIy/348ok3HHJtaLs1nWCSEgg9eJE8XgMvcLZVVpsTb3pPNt8pAvxXCu79q4HSLOIOhvbg87vtT3rVGEEXm3cGqLB5VBnHht2BZuJTRXXWszrOGzDcSY3B8lqOUbRx2g5g3ciY2rFzYjX32vG33ZoY/fkfFW4a5pe0uYGlVzWQ/STHR4aNWyrCEnce8x0ODDm0qvPKhy8Cd0kxrcsqHsjvsyltE4ADclp8dVWoWlLikmyFPdJgoPT8F9ozBZQVLTvxnG56fO/boLJYbU8jKDPG+kVOLqFIC4aHpgVDKv4RsOlJ6IvNyPFvogS7pmL8+cwJP/mymNFW8XgaNpBp8AO3lWecvx5YdCFtxvTAJaWnEPNjm2jkCe/7NVaiyAHh9SUy4INEHseP7++j1nsbSl4tQkuQ9Y7v5qzXGgGS6EVxE2HM+WuIjUigubH1iUZEmmUEJFg+7Uyq7hDF0YjEKzqBW5zoJP89aGgjLOl0Hcze40weQ/JAo1QGZLntHXs86olKu2Qu/O3TdSKTEycpiOsSC4JVTeHaJNrTnc/Sju2AEVpFYNPhN3y+qEuOfYeHuFW9d2UFxRFsmjL8HDzwRFbua1Z6f36AX/plJ9j0PHxlKnXdNDY1BjCuNCx8rTyXV5Lzl1XthsQtSnQw="
env:
  secure: "KWgR8rGPuW/Z7r3ViF1h21C5wwlXQzi3dyvT+bNvI0lY6YLjgW5D69DnQTfdZ2RQPikk5iMV9hb5Olf5G4kcA69UJMZBTE0OxWq3l1/4R0Ul0JGpoZISHg/nCkV3Gd3E+Y+Tdm0nUklh6lpdLl4RieeUxdcNUr6Y9a4ifXk+H5z5uP7o/xx8bzqUrv0bVdzhh2PZsqZvf/uW5OrAQuA3mt+Uc+213gqvPnKYeGDAviQ25DtG2CxOUojBtN2CygSXFu2khOVttMLcCJkSCqbviWfLdTkbFq7IuUIoKuvcA3FP+z/i7DaFmZISylfMR1SS7zLE1bm8yT1cJVDwxcASIDgdv6sOC7m5CNt6xqQLyhO7ud4eLoSnKInW8UmLRy4vvVczDIeOhz9nWVLoWMDGLiChHa0+LEU3dvVmOM8SPumWFa7IRq5i5mx1JA1zv/vp8AZZHMHQWpmmn70K/LEvsSg65VDPF881b0y8df5aFVWRAlJ4G8H2N4PDbiVSgtDpbSbT9QE9tHi1Rh6WSsoo+mI6LGUucayWyeAoDmfupVf6Hhj0+hLSQJT23aefgl1EjBPxKKnevLTWpsA4ugPHT0z0RFSCGQI0G7s17BySdUvOFw7zc7KJauT2XufkyY6QldIyVQYakxZdeKZLZLmecLywt0LKGWqZs4qww7GO1B8="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn -Dmaven.test.failure.ignore=false org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"

after_success:
  - snyk monitor
